version: '3.4'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    env_file: .env
    environment:
      - INFLUXDB_ADMIN_USER=$INFLUXDB_USER
      - INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_PASSWORD
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - ./volumes/influxdb-volume:/var/lib/influxdb
    cpus: 0.50
    networks:
      - speedtest-network

  speedtest:
    image: speedtest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: speedtest
    restart: always
    env_file: .env
    # waiting for db to start and be ready before starting application.
    # command: sh -c './wait-for http://influxdb:8086 -- npm start'
    depends_on:
      - "influxdb"
    environment:
     - NODE_ENV=production
     - INFLUX_URL=influxdb
     - INFLUX_PORT=$INFLUXDB_PORT
     - INFLUXDB_USER=$INFLUXDB_USER
     - INFLUXDB_PASSWORD=$INFLUXDB_PASSWORD
    cpus: 0.50
    networks:
      - speedtest-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "4567:3000"
    networks:
      - speedtest-network
    depends_on:
      - "influxdb"

networks:
  speedtest-network:
    driver: bridge
